title: Copyer.Js
description: Awesome and Minimal Copy Library In Javascript!
tagline: Awesome and Minimal Copy Library In Javascript!

author:
  name: Palash Bauri
  url: https://palash.tk

theme: jekyll-theme-cayman